### ISSUE TITLE
[DownloadRequest] UMBC

### ISSUE THREAD

**Issue by bluefireexplosion** [init6security/DownloadRequestList#10]
We would like to request the following:
Fail2ban - used to prevent brute forcing of ssh and other services
Nmap - used to perform network scans and confirm open or closed ports on boxes we are defending
Clamav - Linux open sourced antivirus scanner 
Thank you!

**Comment by ION28** [comment]
please provide download links (to the exact binary/download you want) or we will not be able to process your request. Thanks so much!

**Comment by bluefireexplosion** [comment]
Got it!
Nmap (rpm, so for RHEL 8 and f34) - https://nmap.org/download.html#linux-rpm
Nmap (deb, so for Ubuntu 18) - https://packages.ubuntu.com/bionic/net/nmap
Fail2ban (rpm) -  https://rpmfind.net/linux/rpm2html/search.php?query=fail2ban&submit=Search+...&system=&arch=
Fail2ban (deb) - https://packages.ubuntu.com/bionic/fail2ban
Clamav (rpm, deb ) - https://www.clamav.net/downloads
iptables-persistent (deb) - https://packages.ubuntu.com/bionic/admin/iptables-persistent
iptables-persistent (rpm) - https://rpmfind.net/linux/RPM/fedora/34/x86_64/i/iptables-1.8.7-3.fc34.x86_64.html
busybox (rpm) - https://rpmfind.net/linux/rpm2html/search.php?query=busybox
busybox (deb) - https://packages.ubuntu.com/bionic/utils/busybox
These should all have the matching binaries, if I understand your setup right for the rpmfind webpages you'd want the fc34 x86_64 arch versions! Apologies I couldn't find more direct links, since f34 is an older release of fedora I couldn't find the links direct from the fedora project.

**Comment by rbohuk** [comment]
Unfortunately Fail2ban will not be permitted during qualifiers because IP blocking will not be allowed

**Comment by bluefireexplosion** [comment]
All good! Are the others alright?

**Comment by rbohuk** [comment]
Look good to me but I'll defer to @jerniman
