### ISSUE TITLE
[DownloadRequest] Capitol Technology University

### ISSUE THREAD

**Issue by co3du5** [init6security/DownloadRequestList#14]
## List
-https://github.com/the-tcpdump-group/tcpdump
-https://nmap.org/
-https://github.com/carlospolop/PEASS-ng/tree/master/winPEAS
-https://github.com/carlospolop/PEASS-ng/tree/master/linPEAS
-https://github.com/cottinghamd/HardeningAuditor
-https://learn.microsoft.com/en-us/windows/win32/winrm/portal
-https://notepad-plus-plus.org/
-https://www.kali.org/tools/nikto/
-https://www.openvas.org/
-https://github.com/SpiderLabs/ModSecurity
-https://github.com/volatilityfoundation/volatility
-https://www.putty.org/
-https://learn.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite
-https://portswigger.net/burp

**Comment by jerniman** [comment]
Got them
