### ISSUE TITLE
[DownloadRequest] Rutgers

### ISSUE THREAD

**Issue by PAndaContron** [init6security/DownloadRequestList#15]
## List

In case not everything can be installed, these are listed in order of preference/importance.

- Microsoft Security Compliance Toolkit 1.0: https://www.microsoft.com/en-us/download/details.aspx?id=55319
  - For hardening Windows systems
- Lynis: https://downloads.cisofy.com/lynis/lynis-3.0.8.tar.gz
  - Useful scanning tool
- Windows Server 2012 R2 Offline Update Installer: https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2023/01/windows8.1-kb5022352-x64_d625561eda52f6d1f768dc444b817af0650ce81f.msu
  - Security patches
- Windows Server 2016 Offline Update Installer: https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/secu/2023/01/windows10.0-kb5022289-x64_79d8b59c2bea46d286f2960920c075f416446445.msu
  - Security patches
- Windows Server 2019 Offline Update Installer: https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2023/01/windows10.0-kb5022286-x64_6e84985d215be67ce1395cb2627b5ee68cf4dcb6.msu
  - Security patches
- Suricata: https://www.openinfosecfoundation.org/download/windows/Suricata-6.0.9-1-64bit.msi (Windows), http://launchpadlibrarian.net/326153260/suricata_3.2-2ubuntu3_amd64.deb (Ubuntu), https://koji.fedoraproject.org/koji/search?terms=suricata-6.0.9-1.fc36&type=build&match=exact (RPM)
  - IDS/IPS
- WinPCAP: https://www.winpcap.org/install/bin/WinPcap_4_1_3.exe
  - Needed for Suricata
- MySQL: https://downloads.mysql.com/archives/get/p/25/file/mysql-installer-community-8.0.31.0.msi
  - For patching
- Postgres: https://www.enterprisedb.com/postgresql-tutorial-resources-training?uuid=7ce7e93f-e1eb-4e42-85fa-84c0c98859ee&campaignId=7012J000001h3GiQAI
  - For patching
- Tiger: http://download.savannah.nongnu.org/releases/tiger/tiger-3.2.3.tar.gz
  - Scanning tool
- OWASP ZAP: https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz
  - Pentesting tool
- Windows 2012 R2 .NET Updates: https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/11/windows8.1-kb5020868-x64_e58bdd248b4679c2271e7ed839525cb8e93790a4.msu
https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/11/windows8.1-kb5020862-x64_4d67610e5283cd7f26ad801b5e37ff4401670601.msu
https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/11/windows8.1-kb5020878-x64-ndp48_f9684f5aa02c3f4cd27a1ca1a55b31f720b275af.msu
  - Security patches
- Windows 2016 .NET Updates: https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/10/windows10.0-kb5020873-x64-ndp48_fadd94443f1d808ca7599eb3457848885e1a552d.msu
  - Security patches
- Windows 2019 .NET Updates: https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/10/windows10.0-kb5020874-x64-ndp48_01a8a26523a2f43e14715e7d33434b094d529233.msu
  - Security patches

Thanks!

**Comment by jerniman** [comment]
Got them with the exception of the updates - the windows OS's will be patched
