### ISSUE TITLE
[DownloadRequest] George Mason University

### ISSUE THREAD

**Issue by Migyaksuil** [init6security/DownloadRequestList#17]
## List
Velociraptor:
https://github.com/Velocidex/velociraptor/releases/download/v0.6.7-5/velociraptor-v0.6.7-4-linux-amd64

Pspy:
https://github.com/DominicBreuker/pspy/releases/download/v1.2.1/pspy64

 Sysdig:
https://github.com/draios/sysdig/releases/download/0.30.2/sysdig-0.30.2-x86_64.deb

**Comment by jerniman** [comment]
Got them
