### ISSUE TITLE
[DownloadRequest]

### ISSUE THREAD

**Issue by Jongk3600** [init6security/DownloadRequestList#2]
Christopher Newport University- for Both Teams

CCDC Framework
- https://github.com/dxrk-kali/autohack

Clam AV
- https://www.clamav.net

Wireshark
- https://www.wireshark.org/download.html

Nessus
- https://www.tenable.com/downloads/nessus?loginAttempted=true

**Comment by ION28** [comment]
For non Github projects, please post the exact download url of the software (ie with the link ending in exe, bin, msi, etc) so we know exactly what software you would like

**Comment by jkaufman0521** [comment]
Clam Link for Linux: https://www.clamav.net/downloads/production/clamav-1.0.0.linux.x86_64.deb
For Windows: https://www.clamav.net/downloads/production/clamav-1.0.0.win.x64.msi

**Comment by jkaufman0521** [comment]
For Nessus, there is no specific download link. We want the windows and linux if possible.
Wireshark Link: https://2.na.dl.wireshark.org/win64/Wireshark-win64-4.0.3.exe

**Comment by jkaufman0521** [comment]
Also, was the GitHub project request approved?

**Comment by jkaufman0521** [comment]
Is there an update on this request?

**Comment by jerniman** [comment]
Got them all.
