### ISSUE TITLE
[DownloadRequest] University of Virginia

### ISSUE THREAD

**Issue by GrantMatteo** [init6security/DownloadRequestList#20]
## List

1. https://github.com/winsiderss/si-builds/releases/download/3.0.5958/systeminformer-3.0.5958-setup.exe
Process Monitoring Tool
2. https://download.mozilla.org/?product=firefox-stub&os=win&lang=en-US
Better web browser for better web browsing
3. http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab
Certificate Checking
4. https://raw.githubusercontent.com/olafhartong/sysmon-modular/master/sysmonconfig.xml
Logging Config
5. https://tinyurl.com 
For ease of access to these links
6. https://raw.githubusercontent.com/bfuzzy/auditd-attack/master/auditd-attack.rules
For better auditing
7. https://sourceforge.net/projects/processhacker/files/processhacker2/processhacker-2.39-bin.zip/download
Earlier version of (1)

If possible, the domain
9. https://artifacts.elastic.co/   
(and the files under it) for Elasticsearch Required Packages

If not, the following (again, Elasticsearch Required Packages)
- https://artifacts.elastic.co/packages/8.x/apt
- https://artifacts.elastic.co/packages/8.x/yum
- https://artifacts.elastic.co/GPG-KEY-elasticsearch
- https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.6.1-amd64.deb
- https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.6.1-x86_64.rpm
- https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.6.1-linux-x86_64.tar.gz
- https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.1-amd64.deb
- https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.1-x86_64.rpm
- https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.1-linux-x86_64.tar.gz
   We realize this would be our 16th link in the case that you cannot provide https://artifacts.elastic.co/. In the case that this becomes a problem, we would prefer this 16th link (https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.1-linux-x86_64.tar.gz) be excluded from our request

**Comment by GrantMatteo** [comment]
These are repeats of other teams, but we wanted to put them here just in case:
1. https://download.sysinternals.com/files/SysinternalsSuite.zip
2. https://github.com/ion28/bluespawn/releases/download/v0.5.1-alpha/bluespawn-client-x64.exe
3. https://github.com/hasherezade/hollows_hunter/releases/download/v0.3.4/hollows_hunter64.exe

**Comment by ION28** [comment]
tinyurl.com is not a piece of software and thus will not be downloaded. There will not generally be internet access within the environment

**Comment by jerniman** [comment]
got them

**Comment by GrantMatteo** [comment]
@jerniman @ION28 Does that mean we weren't able to get (9)?

**Comment by GrantMatteo** [comment]
Edit: Moved to a new post

**Comment by jerniman** [comment]
yes we have number 9
