### ISSUE TITLE
[DownloadRequest] Towson University

### ISSUE THREAD

**Issue by ghouldakidd** [init6security/DownloadRequestList#23]
## List
Hello, these are all the softwares that we would like to use while competing tomorrow
-https://www.wireshark.org/
-(splunk) https://www.splunk.com/en_us/download.html?utm_campaign=google_amer_en_search_brand&utm_source=google&utm_medium=cpc&utm_content=free_trials_downloads&utm_term=splunk&_bk=splunk&_bt=644738781034&_bm=e&_bn=g&_bg=43997962767&device=c&gclid=EAIaIQobChMIo5zE9KD6_AIVS8DICh3KBgkuEAAYASAAEgKDSPD_BwE
- (git) https://www.gitkraken.com/lp/e1?utm_content=optimize-lp&utm_feeditemid=&utm_device=c&utm_term=git&utm_campaign=GK+Git+GUI+-+Search+(US)&utm_source=google&utm_medium=ppc&hsa_acc=1130375851&hsa_cam=16449602314&hsa_grp=136834049231&hsa_ad=585374019835&hsa_src=g&hsa_tgt=kwd-23401250&hsa_kw=git&hsa_mt=b&hsa_net=adwords&hsa_ver=3&gclid=EAIaIQobChMI_8Dg_6D6_AIV8szICh11SQ-oEAAYASAAEgIGOvD_BwE
- (classic x86_64 APT) https://pkgs.org/download/apt
- UFW for ubuntu

**Comment by jerniman** [comment]
The cut off for requests was yesterday at 1900.
