### ISSUE TITLE
[DownloadRequest] Rutgers University

### ISSUE THREAD

**Issue by enderdrag64** [init6security/DownloadRequestList#27]
## List
- https://github.com/atlantsecurity/windows-hardening-scripts
- https://github.com/fail2ban/fail2ban
- https://github.com/BloodHoundAD/BloodHound
- https://github.com/dbeaver/dbeaver
- https://github.com/leizongmin/js-xss
- https://github.com/moh4mmad/Sql-Injection-and-XSS-Protection
- https://learn.microsoft.com/pdf?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows-server%2Fsecurity%2Ftoc.json
- https://learn.microsoft.com/pdf?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows-server%2Fidentity%2Ftoc.json
- https://learn.microsoft.com/pdf?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows-server%2Fadministration%2Ftoc.json
- https://learn.microsoft.com/pdf?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows-server%2Fnetworking%2Ftoc.json
- https://learn.microsoft.com/pdf?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows-server%2Fremote%2Ftoc.json
- https://github.com/swisscom/PowerSponse
- https://github.com/SekoiaLab/Fastir_Collector
- https://github.com/TonyPhipps/Meerkat
- https://www.heidisql.com/downloads/releases/HeidiSQL_12.4_64_Portable.zip
- https://github.com/google/timesketch
- https://github.com/AswinBarath/sql-injection-and-prevention
- https://github.com/julius/node-red-contrib-sqlstring
- https://github.com/mysqljs/sqlstring
- https://fireeye.market/apps/211364
  - I can't give a more direct download link for this one sadly due to the form you have to fill out when you click download

**Comment by enderdrag64** [comment]
Additions: 
- https://www.netresec.com/?download=NetworkMiner
- https://github.com/djarosz/vsftpd
- https://github.com/gpg/gnupg
- https://github.com/mosajjal/binary-tools
- https://github.com/ryanwoodsmall/static-binaries
-  http://launchpadlibrarian.net/101581989/samba-doc-pdf_3.6.3-2ubuntu2_all.deb 
- https://github.com/namazso/OpenHashTab
- https://dbeaver.com/doc/dbeaver.pdf
- https://www.postgresql.org/files/documentation/pdf/15/postgresql-15-US.pdf
- https://downloads.mysql.com/docs/refman-8.0-en.pdf
- https://learn.microsoft.com/pdf?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows-server%2Fstorage%2Ftoc.json
- https://archive.apache.org/dist/httpd/docs/httpd-docs-2.4.16.en.pdf
- https://learn.microsoft.com/pdf?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fsysinternals%2Ftoc.json
- https://www.samba.org/samba/docs/Samba-HOWTO-Collection.pdf

**Comment by enderdrag64** [comment]
Additions:
- https://www.cisco.com/c/en/us/td/docs/security/asa/asa913/asav/getting-started/asav-913-gsg.pdf
- https://docs.paloaltonetworks.com/content/dam/techdocs/en_US/pdf/pan-os/10-1/pan-os-admin/pan-os-admin.pdf

**Comment by mubix** [comment]
No more edits.
