### ISSUE TITLE
[DownloadRequest] UVA

### ISSUE THREAD

**Issue by TheRealChrisM** [init6security/DownloadRequestList#30]
## List
- Paper Server Jar: https://api.papermc.io/v2/projects/paper/versions/1.19.4/builds/477/downloads/paper-1.19.4-477.jar
- Sysinternals Suite: https://download.sysinternals.com/files/SysinternalsSuite.zip
- Process Hacker: https://sourceforge.net/projects/processhacker/files/processhacker2/processhacker-2.39-bin.zip/download
- WinlogBeat: https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-8.6.1-windows-x86_64.zip
- Elasticsearch deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.2-amd64.deb
- Firefox (>:3): https://download.mozilla.org/?product=firefox-stub&os=win&lang=en-US
- Elasticsearch deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.2-amd64.deb
- ElasticSearch GPG Key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- Kibana deb: https://artifacts.elastic.co/downloads/kibana/kibana-8.6.2-amd64.deb
- Elasticsearch rpm: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.2-x86_64.rpm
- Kibana rpm: https://artifacts.elastic.co/downloads/kibana/kibana-8.6.2-x86_64.rpm
- Auditbeat generic: https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.6.2-linux-x86_64.tar.gz
- Auditbeat deb: https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.6.2-amd64.deb
- Auditbeat rpm: https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.6.2-x86_64.rpm
- Filebeat generic: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.1-linux-x86_64.tar.gz
- Filebeat deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.1-amd64.deb
- Filebeat rpm: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.1-x86_64.rpm
- Greylog deb: https://packages.graylog2.org/repo/packages/graylog-sidecar-repository_1-5_all.deb
- Greylog RPM: https://packages.graylog2.org/repo/packages/graylog-sidecar-repository-1-5.noarch.rpm
- System Informer: https://github.com/winsiderss/si-builds/releases/download/3.0.5958/systeminformer-3.0.5958-setup.exe
- Cert Checker: http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab
- Sysmon Config: https://raw.githubusercontent.com/olafhartong/sysmon-modular/master/sysmonconfig.xml
- Auditd rules: https://raw.githubusercontent.com/bfuzzy/auditd-attack/master/auditd-attack.rules
- Bluespawn: https://github.com/ion28/bluespawn/releases/download/v0.5.1-alpha/bluespawn-client-x64.exe
- Hollows Hunter: https://github.com/hasherezade/hollows_hunter/releases/download/v0.3.4/hollows_hunter64.exe
- Microsoft Patch v1: https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2022/12/windows10.0-kb5021235-x64_5d51c0893c43763fff710d3c6bc46feb6446d9f1.msu
- Microsoft Patch v2: https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/secu/2022/09/windows10.0-kb5017396-x64_8db1a993e6115cf3b92d0159f562861ab16ee88d.msu

**Comment by TheRealChrisM** [comment]
List (Addendum)
---
- WinLogBeat [v2]: https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-8.6.2-windows-x86_64.zip
- Filebeat generic [v2]: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.2-linux-x86_64.tar.gz
- Filebeat deb [v2]: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.2-amd64.deb
- Filebeat rpm [v2]: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.6.2-x86_64.rpm

**Comment by Sushi1324** [comment]
LibreOffice Windows Installer: https://www.libreoffice.org/donate/dl/win-x86_64/7.5.1/en-US/LibreOffice_7.5.1_Win_x86-64.msi

**Comment by GrantMatteo** [comment]
Libre Office:
https://download.documentfoundation.org/libreoffice/stable/7.5.1/win/x86_64/LibreOffice_7.5.1_Win_x86-64.msi

DeepGlass
https://github.com/Jack-McDowell/DEEPGLASS/releases/download/1.0.0/DEEPGLASS-x64.exe

Authrootstl:
http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab

Sysmom config:
https://raw.githubusercontent.com/olafhartong/sysmon-modular/master/sysmonconfig.xml
