### ISSUE TITLE
[DownloadRequest] MESSIAH UNIVERSITY

### ISSUE THREAD

**Issue by rt1252** [init6security/DownloadRequestList#6]
## List
- https://www.ossec.net/download-ossec/ - we want to implement file integrity monitoring
- https://atomicorp.com/modsecurity-download/ - we want to implement a web app firewall
- https://www.snort.org/downloads - we want to implement an IDS
- https://learn.microsoft.com/en-us/sysinternals/downloads/ - we want to be able to control file/share permissions, verification, process monitoring, and connection monitoring 
- https://sourceforge.net/projects/rkhunter/files/rkhunter/1.4.6/ - we want to install AV

**Comment by ION28** [comment]
For non Github projects, please post the exact download url of the software (ie with the link ending in exe, bin, msi, etc) so we know exactly what software you would like

**Comment by jerniman** [comment]
Got them.
