### ISSUE TITLE
[DownloadRequest] Regent University 

### ISSUE THREAD

**Issue by DominikLip** [init6security/DownloadRequestList#9]
## List
- https://www.microsoft.com/en-us/download/confirmation.aspx?id=55319&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1
- https://2.na.dl.wireshark.org/win64/Wireshark-win64-4.0.3.exe
- https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
- https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns
- https://learn.microsoft.com/en-us/sysinternals/downloads/procmon
- https://www.microsoft.com/en-us/download/details.aspx?id=46899
- https://www.clamav.net/downloads
- https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer
- https://www.ossec.net/download-ossec/
- https://learn.microsoft.com/en-us/sysinternals/downloads/tcpview
- https://www.monitorix.org/downloads.html
- https://rhel.pkgs.org/8/epel-aarch64/ufw-0.35-14.el8.noarch.rpm.html

**Comment by jerniman** [comment]
Got them
